2024-06-04 18:09:50,045 INFO    StreamThr :11686 [internal.py:wandb_internal():85] W&B internal server running at pid: 11686, started at: 2024-06-04 18:09:50.043849
2024-06-04 18:09:50,048 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: status
2024-06-04 18:09:50,052 INFO    WriterThread:11686 [datastore.py:open_for_write():87] open: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/run-uldcxyhm.wandb
2024-06-04 18:09:50,053 DEBUG   SenderThread:11686 [sender.py:send():378] send: header
2024-06-04 18:09:50,113 DEBUG   SenderThread:11686 [sender.py:send():378] send: run
2024-06-04 18:09:50,830 INFO    SenderThread:11686 [dir_watcher.py:__init__():211] watching files in: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files
2024-06-04 18:09:50,831 INFO    SenderThread:11686 [sender.py:_start_run_threads():1123] run started: uldcxyhm with start time 1717495790.04314
2024-06-04 18:09:50,838 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: check_version
2024-06-04 18:09:50,838 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: check_version
2024-06-04 18:09:51,643 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: run_start
2024-06-04 18:09:51,654 DEBUG   HandlerThread:11686 [system_info.py:__init__():26] System info init
2024-06-04 18:09:51,655 DEBUG   HandlerThread:11686 [system_info.py:__init__():41] System info init done
2024-06-04 18:09:51,655 INFO    HandlerThread:11686 [system_monitor.py:start():194] Starting system monitor
2024-06-04 18:09:51,655 INFO    SystemMonitor:11686 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-04 18:09:51,656 INFO    HandlerThread:11686 [system_monitor.py:probe():214] Collecting system info
2024-06-04 18:09:51,657 INFO    SystemMonitor:11686 [interfaces.py:start():188] Started cpu monitoring
2024-06-04 18:09:51,658 INFO    SystemMonitor:11686 [interfaces.py:start():188] Started disk monitoring
2024-06-04 18:09:51,659 INFO    SystemMonitor:11686 [interfaces.py:start():188] Started gpu monitoring
2024-06-04 18:09:51,660 INFO    SystemMonitor:11686 [interfaces.py:start():188] Started memory monitoring
2024-06-04 18:09:51,662 INFO    SystemMonitor:11686 [interfaces.py:start():188] Started network monitoring
2024-06-04 18:09:51,674 DEBUG   HandlerThread:11686 [system_info.py:probe():150] Probing system
2024-06-04 18:09:51,681 DEBUG   HandlerThread:11686 [system_info.py:_probe_git():135] Probing git
2024-06-04 18:09:51,693 DEBUG   HandlerThread:11686 [system_info.py:_probe_git():143] Probing git done
2024-06-04 18:09:51,693 DEBUG   HandlerThread:11686 [system_info.py:probe():198] Probing system done
2024-06-04 18:09:51,693 DEBUG   HandlerThread:11686 [system_monitor.py:probe():223] {'os': 'Linux-5.4.0-99-generic-x86_64-with-glibc2.17', 'python': '3.8.10', 'heartbeatAt': '2024-06-04T10:09:51.674912', 'startedAt': '2024-06-04T10:09:50.037981', 'docker': None, 'cuda': None, 'args': ('--model_name_or_path', './checkpoints/vicuna-7b-v1.5-16k', '--version', 'v1', '--data_path', './data/discharge/st_gpt.json', '--st_content', './TAXI.json', '--st_data_path', './data/discharge/st_data.pkl', '--st_tower', 'ST_Encoder', '--tune_st_mlp_adapter', 'True', '--st_select_layer', '-2', '--use_st_start_end', '--fp16', 'True', '--output_dir', './checkpoints/UrbanGPT', '--num_train_epochs', '3', '--per_device_train_batch_size', '4', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '4', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '4800', '--save_total_limit', '1', '--learning_rate', '2e-3', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'False', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--lazy_preprocess', 'True', '--report_to', 'wandb'), 'state': 'running', 'program': 'urbangpt/train/train_mem.py', 'codePathLocal': 'urbangpt/train/train_mem.py', 'codePath': 'urbangpt/train/train_mem.py', 'git': {'remote': 'https://github.com/TobyYang7/STllama.git', 'commit': '8448b7de864dfbd0a2e72588f50828d5093a4b50'}, 'email': 'tobyyang7@foxmail.com', 'root': '/root/autodl-tmp/STllama', 'host': 'autodl-container-7bda11a2fa-d300d1c6', 'username': 'root', 'executable': '/root/miniconda3/bin/python', 'cpu_count': 40, 'cpu_count_logical': 80, 'cpu_freq': {'current': 3000.0279999999975, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}, {'current': 3000.028, 'min': 0.0, 'max': 0.0}], 'disk': {'/': {'total': 30.0, 'used': 22.363609313964844}}, 'gpu': 'Tesla V100S-PCIE-32GB', 'gpu_count': 1, 'gpu_devices': [{'name': 'Tesla V100S-PCIE-32GB', 'memory_total': 34359738368}], 'memory': {'total': 629.8885612487793}}
2024-06-04 18:09:51,694 INFO    HandlerThread:11686 [system_monitor.py:probe():224] Finished collecting system info
2024-06-04 18:09:51,694 INFO    HandlerThread:11686 [system_monitor.py:probe():227] Publishing system info
2024-06-04 18:09:51,694 DEBUG   HandlerThread:11686 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-06-04 18:09:51,832 INFO    Thread-12 :11686 [dir_watcher.py:_on_file_created():271] file/dir created: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/conda-environment.yaml
2024-06-04 18:09:52,212 DEBUG   HandlerThread:11686 [system_info.py:_save_conda():222] Saving conda packages done
2024-06-04 18:09:52,214 INFO    HandlerThread:11686 [system_monitor.py:probe():229] Finished publishing system info
2024-06-04 18:09:52,219 DEBUG   SenderThread:11686 [sender.py:send():378] send: files
2024-06-04 18:09:52,219 INFO    SenderThread:11686 [sender.py:_save_file():1389] saving file wandb-metadata.json with policy now
2024-06-04 18:09:52,377 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: python_packages
2024-06-04 18:09:52,377 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: python_packages
2024-06-04 18:09:52,378 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: stop_status
2024-06-04 18:09:52,379 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: stop_status
2024-06-04 18:09:52,795 DEBUG   SenderThread:11686 [sender.py:send():378] send: telemetry
2024-06-04 18:09:52,795 DEBUG   SenderThread:11686 [sender.py:send():378] send: config
2024-06-04 18:09:52,796 DEBUG   SenderThread:11686 [sender.py:send():378] send: metric
2024-06-04 18:09:52,796 DEBUG   SenderThread:11686 [sender.py:send():378] send: telemetry
2024-06-04 18:09:52,796 DEBUG   SenderThread:11686 [sender.py:send():378] send: telemetry
2024-06-04 18:09:52,796 DEBUG   SenderThread:11686 [sender.py:send():378] send: metric
2024-06-04 18:09:52,796 WARNING SenderThread:11686 [sender.py:send_metric():1340] Seen metric with glob (shouldn't happen)
2024-06-04 18:09:52,820 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-metadata.json?Expires=1717582192&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Xo24BWVCuDpKr1TJTu4ro7h1c4BcraKQFKPu7t4L5JeZMkyLLX1oiciireraGN2miVoVzPvb5LbC9rIutLQ2MULMNnIKucJSDmgUyHpyV51VC2cokS2O8HG4QaQ%2F%2FUdNtW1IdehQHrwHBkWAWuL6BkwM01axf3aSpmGx%2F74rzFibymL1LQ%2Fg7npoMGvm1qdPECGDe7cCvccQRV0SENt5WO5oVYri3g%2FkOnnwGs991KRdQ1o20myjJuEoYbv9N9OQvOYoJp9HUgo8cjGZ5uX4ZC4q5vKYA1%2FCDo7sPvQOC9vtWWCK%2FmIRTS5QM%2BcD7Y9Z2mU3Nv8Mb35WRyOWVjX5cg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:09:52,820 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10734'}
2024-06-04 18:09:52,821 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:09:52,832 INFO    Thread-12 :11686 [dir_watcher.py:_on_file_created():271] file/dir created: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/output.log
2024-06-04 18:09:52,832 INFO    Thread-12 :11686 [dir_watcher.py:_on_file_created():271] file/dir created: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/requirements.txt
2024-06-04 18:09:52,832 INFO    Thread-12 :11686 [dir_watcher.py:_on_file_created():271] file/dir created: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/wandb-metadata.json
2024-06-04 18:09:53,637 DEBUG   SenderThread:11686 [sender.py:send():378] send: exit
2024-06-04 18:09:53,637 INFO    SenderThread:11686 [sender.py:send_exit():585] handling exit code: 1
2024-06-04 18:09:53,637 INFO    SenderThread:11686 [sender.py:send_exit():587] handling runtime: 1
2024-06-04 18:09:53,640 INFO    SenderThread:11686 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-06-04 18:09:53,640 INFO    SenderThread:11686 [sender.py:send_exit():593] send defer
2024-06-04 18:09:53,640 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:53,640 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 0
2024-06-04 18:09:53,641 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:53,641 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 0
2024-06-04 18:09:53,641 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 1
2024-06-04 18:09:53,641 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:53,641 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 1
2024-06-04 18:09:53,641 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:53,641 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 1
2024-06-04 18:09:53,641 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 2
2024-06-04 18:09:53,642 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:53,642 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 2
2024-06-04 18:09:53,642 INFO    HandlerThread:11686 [system_monitor.py:finish():203] Stopping system monitor
2024-06-04 18:09:53,642 DEBUG   SystemMonitor:11686 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-04 18:09:53,642 DEBUG   SystemMonitor:11686 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-04 18:09:53,642 DEBUG   SystemMonitor:11686 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-04 18:09:53,643 INFO    HandlerThread:11686 [interfaces.py:finish():200] Joined cpu monitor
2024-06-04 18:09:53,644 INFO    HandlerThread:11686 [interfaces.py:finish():200] Joined disk monitor
2024-06-04 18:09:53,667 INFO    HandlerThread:11686 [interfaces.py:finish():200] Joined gpu monitor
2024-06-04 18:09:53,667 INFO    HandlerThread:11686 [interfaces.py:finish():200] Joined memory monitor
2024-06-04 18:09:53,667 INFO    HandlerThread:11686 [interfaces.py:finish():200] Joined network monitor
2024-06-04 18:09:53,668 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:53,668 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 2
2024-06-04 18:09:53,668 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 3
2024-06-04 18:09:53,668 DEBUG   SenderThread:11686 [sender.py:send():378] send: stats
2024-06-04 18:09:53,669 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:53,669 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 3
2024-06-04 18:09:53,669 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:53,669 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 3
2024-06-04 18:09:53,669 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 4
2024-06-04 18:09:53,669 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:53,669 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 4
2024-06-04 18:09:53,670 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:53,670 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 4
2024-06-04 18:09:53,670 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 5
2024-06-04 18:09:53,670 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:53,670 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 5
2024-06-04 18:09:53,670 DEBUG   SenderThread:11686 [sender.py:send():378] send: summary
2024-06-04 18:09:53,672 INFO    SenderThread:11686 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-06-04 18:09:53,672 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:53,672 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 5
2024-06-04 18:09:53,672 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 6
2024-06-04 18:09:53,672 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:53,672 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 6
2024-06-04 18:09:53,673 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:53,673 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 6
2024-06-04 18:09:53,677 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: status_report
2024-06-04 18:09:53,832 INFO    Thread-12 :11686 [dir_watcher.py:_on_file_created():271] file/dir created: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/wandb-summary.json
2024-06-04 18:09:53,986 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 7
2024-06-04 18:09:53,986 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:53,987 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 7
2024-06-04 18:09:53,987 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:53,987 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 7
2024-06-04 18:09:54,085 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-metadata.json?Expires=1717582192&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Xo24BWVCuDpKr1TJTu4ro7h1c4BcraKQFKPu7t4L5JeZMkyLLX1oiciireraGN2miVoVzPvb5LbC9rIutLQ2MULMNnIKucJSDmgUyHpyV51VC2cokS2O8HG4QaQ%2F%2FUdNtW1IdehQHrwHBkWAWuL6BkwM01axf3aSpmGx%2F74rzFibymL1LQ%2Fg7npoMGvm1qdPECGDe7cCvccQRV0SENt5WO5oVYri3g%2FkOnnwGs991KRdQ1o20myjJuEoYbv9N9OQvOYoJp9HUgo8cjGZ5uX4ZC4q5vKYA1%2FCDo7sPvQOC9vtWWCK%2FmIRTS5QM%2BcD7Y9Z2mU3Nv8Mb35WRyOWVjX5cg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:09:54,085 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10734'}
2024-06-04 18:09:54,085 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:09:54,636 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: poll_exit
2024-06-04 18:09:54,803 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 8
2024-06-04 18:09:54,803 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: poll_exit
2024-06-04 18:09:54,804 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:54,804 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 8
2024-06-04 18:09:54,804 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:09:54,804 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 8
2024-06-04 18:09:54,804 INFO    SenderThread:11686 [job_builder.py:build():432] Attempting to build job artifact
2024-06-04 18:09:54,806 INFO    SenderThread:11686 [job_builder.py:_get_source_type():565] is repo sourced job
2024-06-04 18:09:54,834 INFO    Thread-12 :11686 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/config.yaml
2024-06-04 18:09:54,835 INFO    Thread-12 :11686 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/output.log
2024-06-04 18:09:54,836 INFO    SenderThread:11686 [job_builder.py:build():541] adding wandb-job metadata file
2024-06-04 18:09:54,843 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 9
2024-06-04 18:09:54,843 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:09:54,843 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 9
2024-06-04 18:09:54,843 DEBUG   SenderThread:11686 [sender.py:send():378] send: artifact
2024-06-04 18:09:55,638 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: poll_exit
2024-06-04 18:09:56,370 INFO    wandb-upload_1:11686 [upload_job.py:push():85] Skipped uploading /root/.local/share/wandb/artifacts/staging/tmp_lunot67
2024-06-04 18:09:56,607 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-metadata.json?Expires=1717582192&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Xo24BWVCuDpKr1TJTu4ro7h1c4BcraKQFKPu7t4L5JeZMkyLLX1oiciireraGN2miVoVzPvb5LbC9rIutLQ2MULMNnIKucJSDmgUyHpyV51VC2cokS2O8HG4QaQ%2F%2FUdNtW1IdehQHrwHBkWAWuL6BkwM01axf3aSpmGx%2F74rzFibymL1LQ%2Fg7npoMGvm1qdPECGDe7cCvccQRV0SENt5WO5oVYri3g%2FkOnnwGs991KRdQ1o20myjJuEoYbv9N9OQvOYoJp9HUgo8cjGZ5uX4ZC4q5vKYA1%2FCDo7sPvQOC9vtWWCK%2FmIRTS5QM%2BcD7Y9Z2mU3Nv8Mb35WRyOWVjX5cg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:09:56,607 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10734'}
2024-06-04 18:09:56,607 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:09:56,644 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/181782398/859765561/f14b3dbf2547b3e520fc5c05858910cd?Expires=1717582196&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R%2FlgeNn%2FJAgs4w7OGwQ0ZoO9q0bfq7VOBN%2Fz6YBiy8OfxSRRkn3hWCB4T79D83hyvA9UmApNI11ANc%2FKuaKUPRnz7ahcmKcWzUf0QEsEwOzPcXWWWtTJXPX0U%2F6clUMDh2eMY3mp22f2pGhave5yiMO7i4m6befmZtZWutJjXhXjVK%2F8YVRXBqRv2MEKacL5dJAurOzQ5Pr2zAvPwthU%2F9FB9t%2BBi0I6HVS7unIHkrjcJhBQgDQ6ho4CADoCT95bxqHLe7McRblw%2Bl3DOZ5Qa58%2Ft02RO9b4gdxxXC9vAnjHWMweeTyR5Bja1jpcVNcBpNITemM19uhdFCJFNqeyfQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:09:56,644 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '8Us9vyVHs+Ug/FwFhYkQzQ==', 'Content-Type': 'application/json', 'Content-Length': '23149'}
2024-06-04 18:09:56,644 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:09:57,901 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/181782398/859765561/f14b3dbf2547b3e520fc5c05858910cd?Expires=1717582196&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R%2FlgeNn%2FJAgs4w7OGwQ0ZoO9q0bfq7VOBN%2Fz6YBiy8OfxSRRkn3hWCB4T79D83hyvA9UmApNI11ANc%2FKuaKUPRnz7ahcmKcWzUf0QEsEwOzPcXWWWtTJXPX0U%2F6clUMDh2eMY3mp22f2pGhave5yiMO7i4m6befmZtZWutJjXhXjVK%2F8YVRXBqRv2MEKacL5dJAurOzQ5Pr2zAvPwthU%2F9FB9t%2BBi0I6HVS7unIHkrjcJhBQgDQ6ho4CADoCT95bxqHLe7McRblw%2Bl3DOZ5Qa58%2Ft02RO9b4gdxxXC9vAnjHWMweeTyR5Bja1jpcVNcBpNITemM19uhdFCJFNqeyfQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:09:57,901 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '8Us9vyVHs+Ug/FwFhYkQzQ==', 'Content-Type': 'application/json', 'Content-Length': '23149'}
2024-06-04 18:09:57,901 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:09:57,901 INFO    wandb-upload_2:11686 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2731, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2762, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2731, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-06-04 18:10:00,485 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/181782398/859765561/f14b3dbf2547b3e520fc5c05858910cd?Expires=1717582196&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R%2FlgeNn%2FJAgs4w7OGwQ0ZoO9q0bfq7VOBN%2Fz6YBiy8OfxSRRkn3hWCB4T79D83hyvA9UmApNI11ANc%2FKuaKUPRnz7ahcmKcWzUf0QEsEwOzPcXWWWtTJXPX0U%2F6clUMDh2eMY3mp22f2pGhave5yiMO7i4m6befmZtZWutJjXhXjVK%2F8YVRXBqRv2MEKacL5dJAurOzQ5Pr2zAvPwthU%2F9FB9t%2BBi0I6HVS7unIHkrjcJhBQgDQ6ho4CADoCT95bxqHLe7McRblw%2Bl3DOZ5Qa58%2Ft02RO9b4gdxxXC9vAnjHWMweeTyR5Bja1jpcVNcBpNITemM19uhdFCJFNqeyfQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:00,485 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '8Us9vyVHs+Ug/FwFhYkQzQ==', 'Content-Type': 'application/json', 'Content-Length': '23149'}
2024-06-04 18:10:00,485 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:00,641 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: keepalive
2024-06-04 18:10:01,713 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-metadata.json?Expires=1717582192&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Xo24BWVCuDpKr1TJTu4ro7h1c4BcraKQFKPu7t4L5JeZMkyLLX1oiciireraGN2miVoVzPvb5LbC9rIutLQ2MULMNnIKucJSDmgUyHpyV51VC2cokS2O8HG4QaQ%2F%2FUdNtW1IdehQHrwHBkWAWuL6BkwM01axf3aSpmGx%2F74rzFibymL1LQ%2Fg7npoMGvm1qdPECGDe7cCvccQRV0SENt5WO5oVYri3g%2FkOnnwGs991KRdQ1o20myjJuEoYbv9N9OQvOYoJp9HUgo8cjGZ5uX4ZC4q5vKYA1%2FCDo7sPvQOC9vtWWCK%2FmIRTS5QM%2BcD7Y9Z2mU3Nv8Mb35WRyOWVjX5cg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:01,713 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10734'}
2024-06-04 18:10:01,713 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:05,461 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/181782398/859765561/f14b3dbf2547b3e520fc5c05858910cd?Expires=1717582196&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R%2FlgeNn%2FJAgs4w7OGwQ0ZoO9q0bfq7VOBN%2Fz6YBiy8OfxSRRkn3hWCB4T79D83hyvA9UmApNI11ANc%2FKuaKUPRnz7ahcmKcWzUf0QEsEwOzPcXWWWtTJXPX0U%2F6clUMDh2eMY3mp22f2pGhave5yiMO7i4m6befmZtZWutJjXhXjVK%2F8YVRXBqRv2MEKacL5dJAurOzQ5Pr2zAvPwthU%2F9FB9t%2BBi0I6HVS7unIHkrjcJhBQgDQ6ho4CADoCT95bxqHLe7McRblw%2Bl3DOZ5Qa58%2Ft02RO9b4gdxxXC9vAnjHWMweeTyR5Bja1jpcVNcBpNITemM19uhdFCJFNqeyfQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:05,462 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '8Us9vyVHs+Ug/FwFhYkQzQ==', 'Content-Type': 'application/json', 'Content-Length': '23149'}
2024-06-04 18:10:05,462 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:05,644 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: keepalive
2024-06-04 18:10:10,647 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: keepalive
2024-06-04 18:10:11,857 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-metadata.json?Expires=1717582192&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Xo24BWVCuDpKr1TJTu4ro7h1c4BcraKQFKPu7t4L5JeZMkyLLX1oiciireraGN2miVoVzPvb5LbC9rIutLQ2MULMNnIKucJSDmgUyHpyV51VC2cokS2O8HG4QaQ%2F%2FUdNtW1IdehQHrwHBkWAWuL6BkwM01axf3aSpmGx%2F74rzFibymL1LQ%2Fg7npoMGvm1qdPECGDe7cCvccQRV0SENt5WO5oVYri3g%2FkOnnwGs991KRdQ1o20myjJuEoYbv9N9OQvOYoJp9HUgo8cjGZ5uX4ZC4q5vKYA1%2FCDo7sPvQOC9vtWWCK%2FmIRTS5QM%2BcD7Y9Z2mU3Nv8Mb35WRyOWVjX5cg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:11,857 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10734'}
2024-06-04 18:10:11,858 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:15,397 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/181782398/859765561/f14b3dbf2547b3e520fc5c05858910cd?Expires=1717582196&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R%2FlgeNn%2FJAgs4w7OGwQ0ZoO9q0bfq7VOBN%2Fz6YBiy8OfxSRRkn3hWCB4T79D83hyvA9UmApNI11ANc%2FKuaKUPRnz7ahcmKcWzUf0QEsEwOzPcXWWWtTJXPX0U%2F6clUMDh2eMY3mp22f2pGhave5yiMO7i4m6befmZtZWutJjXhXjVK%2F8YVRXBqRv2MEKacL5dJAurOzQ5Pr2zAvPwthU%2F9FB9t%2BBi0I6HVS7unIHkrjcJhBQgDQ6ho4CADoCT95bxqHLe7McRblw%2Bl3DOZ5Qa58%2Ft02RO9b4gdxxXC9vAnjHWMweeTyR5Bja1jpcVNcBpNITemM19uhdFCJFNqeyfQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:15,397 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '8Us9vyVHs+Ug/FwFhYkQzQ==', 'Content-Type': 'application/json', 'Content-Length': '23149'}
2024-06-04 18:10:15,397 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:15,650 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: keepalive
2024-06-04 18:10:20,652 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: keepalive
2024-06-04 18:10:25,655 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: keepalive
2024-06-04 18:10:28,552 INFO    wandb-upload_0:11686 [upload_job.py:push():130] Uploaded file /tmp/tmpvhidmpurwandb/63ofmwoy-wandb-metadata.json
2024-06-04 18:10:30,657 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: keepalive
2024-06-04 18:10:35,632 INFO    wandb-upload_2:11686 [upload_job.py:push():88] Uploaded file /tmp/tmpkoldrej3/wandb-job.json
2024-06-04 18:10:35,660 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: keepalive
2024-06-04 18:10:37,168 INFO    SenderThread:11686 [sender.py:send_artifact():1467] sent artifact job-https___github.com_TobyYang7_STllama.git_urbangpt_train_train_mem.py - {'id': 'QXJ0aWZhY3Q6ODU5NzY1NTYx', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE4MTc4MjM5OA==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6ODU5NzIxOTE4', 'versionIndex': 0}}}
2024-06-04 18:10:37,168 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:10:37,168 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 9
2024-06-04 18:10:37,168 INFO    SenderThread:11686 [dir_watcher.py:finish():358] shutting down directory watcher
2024-06-04 18:10:37,168 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: status_report
2024-06-04 18:10:37,844 INFO    SenderThread:11686 [dir_watcher.py:finish():388] scan: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files
2024-06-04 18:10:37,844 INFO    SenderThread:11686 [dir_watcher.py:finish():402] scan save: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/config.yaml config.yaml
2024-06-04 18:10:37,844 INFO    SenderThread:11686 [dir_watcher.py:finish():402] scan save: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/conda-environment.yaml conda-environment.yaml
2024-06-04 18:10:37,845 INFO    SenderThread:11686 [dir_watcher.py:finish():402] scan save: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/wandb-metadata.json wandb-metadata.json
2024-06-04 18:10:37,845 INFO    SenderThread:11686 [dir_watcher.py:finish():402] scan save: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/requirements.txt requirements.txt
2024-06-04 18:10:37,845 INFO    SenderThread:11686 [dir_watcher.py:finish():402] scan save: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/output.log output.log
2024-06-04 18:10:37,845 INFO    SenderThread:11686 [dir_watcher.py:finish():402] scan save: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/wandb-summary.json wandb-summary.json
2024-06-04 18:10:37,845 INFO    SenderThread:11686 [sender.py:transition_state():613] send defer: 10
2024-06-04 18:10:37,845 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: poll_exit
2024-06-04 18:10:37,848 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: defer
2024-06-04 18:10:37,848 INFO    HandlerThread:11686 [handler.py:handle_request_defer():184] handle defer: 10
2024-06-04 18:10:37,854 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: defer
2024-06-04 18:10:37,854 INFO    SenderThread:11686 [sender.py:send_request_defer():609] handle sender defer: 10
2024-06-04 18:10:37,854 INFO    SenderThread:11686 [file_pusher.py:finish():169] shutting down file pusher
2024-06-04 18:10:38,215 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:38,216 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:10:38,216 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:38,337 ERROR   wandb-upload_3:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/output.log?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=X4w8J0dPnUiLQzhircJHITO%2FxfgX2sJg2jnOxYvj6a5ImLvZYsThd%2BnEcp9RmUudvkLZXu79kBGaDHzSTuonkwfJuU539FfgZGhjYagC%2BhTXwYJd0O4tpHT2VUrR6%2FLkLb%2BcU%2FlXQjQo1lfZImwuXczPRXlojJPc%2FQTNKxPCSfLOFYyhz5ax83wMaByTavFejgSCYi9H56k3jymqoL31WaVZehocsoeIGRlOkbcjSIq6IkvGFKUNr%2BLo3NIZ5ITUlCLwkDvsgAmoS93dS3oxqjvNlizf0C5Yg%2FIMw22hZl%2BraKsRHclz4CmjXQCx9lP5WqS95OSCCd%2BBvRkkRsqT7Q%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:38,337 ERROR   wandb-upload_3:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2033'}
2024-06-04 18:10:38,337 ERROR   wandb-upload_3:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:38,415 INFO    wandb-upload_1:11686 [upload_job.py:push():130] Uploaded file /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/config.yaml
2024-06-04 18:10:38,501 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:38,501 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:10:38,501 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:38,662 DEBUG   HandlerThread:11686 [handler.py:handle_request():158] handle_request: poll_exit
2024-06-04 18:10:38,663 DEBUG   SenderThread:11686 [sender.py:send_request():405] send_request: poll_exit
2024-06-04 18:10:39,104 WARNING StreamThr :11686 [internal.py:is_dead():413] Internal process exiting, parent pid 11131 disappeared
2024-06-04 18:10:39,104 ERROR   StreamThr :11686 [internal.py:wandb_internal():151] Internal process shutdown.
2024-06-04 18:10:39,570 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:39,570 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:10:39,571 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:39,571 INFO    wandb-upload_0:11686 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2731, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2762, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2731, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-06-04 18:10:39,662 INFO    HandlerThread:11686 [handler.py:finish():882] shutting down handler
2024-06-04 18:10:39,663 INFO    WriterThread:11686 [datastore.py:close():296] close: /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/run-uldcxyhm.wandb
2024-06-04 18:10:39,663 INFO    SenderThread:11686 [sender.py:finish():1545] shutting down sender
2024-06-04 18:10:39,663 INFO    SenderThread:11686 [file_pusher.py:finish():169] shutting down file pusher
2024-06-04 18:10:39,663 INFO    SenderThread:11686 [file_pusher.py:join():175] waiting for file pusher
2024-06-04 18:10:39,738 INFO    wandb-upload_3:11686 [upload_job.py:push():130] Uploaded file /root/autodl-tmp/STllama/wandb/run-20240604_180950-uldcxyhm/files/output.log
2024-06-04 18:10:39,994 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:39,994 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:10:39,994 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:41,936 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:41,936 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:10:41,936 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:42,327 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:42,327 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:10:42,327 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:46,588 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:46,588 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:10:46,588 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:46,943 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:46,944 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:10:46,944 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:54,996 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:54,996 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:10:54,996 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:10:56,699 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:10:56,699 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:10:56,699 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:11:13,861 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:11:13,862 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:11:13,862 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:11:16,119 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:11:16,119 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:11:16,119 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:11:46,164 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:11:46,165 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:11:46,165 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:11:49,076 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:11:49,076 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:11:49,076 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:12:53,660 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:12:53,660 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:12:53,660 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:13:00,271 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:13:00,271 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:13:00,271 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:15:07,409 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/requirements.txt?Expires=1717582237&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=v9XUlK6lMWXI%2F7Gbx37jZoBAccC0%2B%2Fjx0Hls7yEpRDWd1i9Mh2L%2F0JWW2h1C1%2BF4MizhmoSL9M9PRSsYkW%2BccVuC0Dshkaw03P2mhnttUIuUxe9YbxKPv38e5H1wa%2B1u8auRWRGgw7r%2FqbxmELJpO8kCrCe5CKcz3VASnS%2B%2BNH0qcCecwL%2BTqHgni9bHbYL%2FjepiHhVWeCow4cLqlp2zqXuqcNNrz2gLqmeJosnl6ZHiV3ikb%2B3u%2FyvjzMVUXIYchou1S9A4dA6vTCbySbBIh2BNGA2QZc6u5ku44H3Vwp71L05pLDP9i649%2B4ucz%2F3KKXMvYnpYcHovhIqYPWiO0g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:15:07,409 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4328'}
2024-06-04 18:15:07,409 ERROR   wandb-upload_0:11686 [internal_api.py:upload_file():2742] upload_file response body: 
2024-06-04 18:15:36,390 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2738] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/toby-yang/huggingface/uldcxyhm/wandb-summary.json?Expires=1717582238&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=xHcKTKCJtV%2B1E9bIeoDQhzW6IWJTQ%2BuWgZaTu2P1A9MavECAiZoIWGyUJKAJytqO84J5%2BNXqds%2B7n0K9t4Ak%2Byxy25kvWpo0uEHGgo%2BzYGm2nuPTtM9zjzDw2nwHjlOeLtwbgrfrn6xw%2BZ3q77bl6HPOIx58svheHmyWREI40ghJQ0J9SaIqPaf64d1LCTwyiIUWdnCaMFCtiUobYg7YN02D6qxwWaEdK8KkrZGoM%2FjKNUEFlQexA%2BnxwIiHukI0xfM9GNivMczJbGBIG9OyetYKKzPSUXXlWQrWdAwD32UzE6ccMvNnNoXlHRpjpis9%2FHjF6IaG6hEa%2FnXHaiDBow%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-06-04 18:15:36,390 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2740] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2024-06-04 18:15:36,390 ERROR   wandb-upload_2:11686 [internal_api.py:upload_file():2742] upload_file response body: 
